version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    flags:
      - -pgo=cpu.pprof
    main: ./cmd/mkbrr/
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}

  # mkbrr-gui is built separately:
  # - macOS: using 'fyne package' on macOS runner (universal binary)
  # - Windows: using 'fyne-cross' on Linux runner
  # - Linux: using 'fyne-cross' on Linux runner
archives:
  # CLI tool archive
  - id: mkbrr
    ids:
      - mkbrr
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

  # Windows amd64 GUI Archive
  - id: mkbrr-gui-windows-amd64
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      windows_x86_64
    meta: true # Create archive without binaries, just pre-built files
    files:
      - src: fyne-cross/bin/windows-amd64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

  # Windows arm64 GUI Archive
  - id: mkbrr-gui-windows-arm64
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      windows_arm64
    meta: true # Create archive without binaries, just pre-built files
    files:
      - src: fyne-cross/bin/windows-arm64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

  # Linux amd64 GUI Archive
  - id: mkbrr-gui-linux-amd64
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      linux_x86_64
    meta: true # Create archive without binaries, just pre-built files
    files:
      - src: fyne-cross/bin/linux-amd64/mkbrr-gui
        dst: mkbrr-gui

  # Linux arm64 GUI Archive
  - id: mkbrr-gui-linux-arm64
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      linux_arm64
    meta: true # Create archive without binaries, just pre-built files
    files:
      - src: fyne-cross/bin/linux-arm64/mkbrr-gui
        dst: mkbrr-gui

release:
  prerelease: auto
  # Attach the pre-built DMG directly as an extra file
  extra_files:
    - glob: ./dist/mkbrr-gui-darwin-universal.dmg
      name_template: "{{ .ProjectName }}-gui_{{ .Version }}_darwin_universal.dmg"
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# TODO: Add nfpms config for mkbrr-gui
