version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    flags:
      - -pgo=cpu.pprof
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./main.go
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - --key=env://COSIGN_PRIVATE_KEY
      - --output-signature=${signature}
      - --yes
      - ${artifact}
    env:
      - COSIGN_PRIVATE_KEY={{ .Env.COSIGN_PRIVATE_KEY }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

announce:
  skip: false
  twitter:
    enabled: true
    message_template: 'mkbrr {{ .Tag }} has been released! Check it out at {{ .ReleaseURL }}'

gomod:
  proxy: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'
  format: 'tar.gz'