version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    # flags: # PGO flag removed during simplification, can be re-added if needed
    #   - -pgo=cpu.pprof
    main: ./cmd/mkbrr/
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}

  # mkbrr-gui is built separately:
  # - macOS: using 'fyne package' on macOS runner (universal binary)
  # - Windows: using 'fyne-cross' on Linux runner
archives:
  # CLI tool archive
  - id: mkbrr
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
  
  # GUI Archive (Handles macOS and Windows pre-built binaries)
  - id: mkbrr-gui
    # No top-level 'builds' reference as mkbrr-gui is built externally
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
      - goos: darwin
        formats: [ 'tar.gz' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Os "darwin" }}universal
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    
    # Define overrides for specific platforms to include the correct files
    overrides:
      # macOS universal build (applies to darwin/amd64 and darwin/arm64)
      - goos: darwin
        files:
          - src: dist/darwin/mkbrr-gui-darwin-universal.zip
            dst: . # Include the zip file itself in the archive root
      
      # Windows amd64 build
      - goos: windows
        goarch: amd64
        files:
          - src: dist/windows/amd64/mkbrr-gui.exe
            dst: mkbrr-gui.exe
      
      # Windows arm64 build
      - goos: windows
        goarch: arm64
        files:
          - src: dist/windows/arm64/mkbrr-gui.exe
            dst: mkbrr-gui.exe # Using same name as amd64 for simplicity
    
    # Ignore platforms for which we don't have pre-built GUI binaries
    ignore:
      - goos: linux # Ignore all linux targets
      - goos: windows
        goarch: '386' # Ignore windows 386

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# TODO: Add nfpms config for mkbrr-gui if desired
