version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    # flags: # PGO flag removed during simplification, can be re-added if needed
    #   - -pgo=cpu.pprof
    main: ./cmd/mkbrr/
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}

  # mkbrr-gui is built separately:
  # - macOS: using 'fyne package' on macOS runner (universal binary)
  # - Windows: using 'fyne-cross' on Linux runner
archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
  # macOS GUI Archive (Universal)
  - id: mkbrr-gui-darwin
    goos: [darwin]
    goarch: [amd64, arm64] # Apply this rule for both darwin targets
    # No format override needed, tar.gz is default for darwin
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      universal # Explicitly name the universal archive
    files:
      - src: dist/darwin/mkbrr-gui-darwin-universal.zip # The zip created by the workflow
        dst: mkbrr-gui-darwin-universal.zip # Include the zip itself in the final release archive

  # Windows amd64 GUI Archive
  - id: mkbrr-gui-windows-amd64
    goos: [windows]
    goarch: [amd64]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      x86_64
    files:
      - src: dist/windows/amd64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

  # Windows arm64 GUI Archive
  - id: mkbrr-gui-windows-arm64
    goos: [windows]
    goarch: [arm64]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      arm64
    files:
      - src: dist/windows/arm64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# TODO: Add nfpms config for mkbrr-gui if desired
