version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    # flags: # PGO flag removed during simplification, can be re-added if needed
    #   - -pgo=cpu.pprof
    main: ./cmd/mkbrr/
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}
      
  # Dummy build for macOS GUI target
  - id: mkbrr-gui-darwin-target
    main: ./cmd/mkbrr-gui/
    binary: ignored-darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    skip: true  # Don't actually build this

  # Dummy build for Windows amd64 GUI target
  - id: mkbrr-gui-windows-amd64-target
    main: ./cmd/mkbrr-gui/
    binary: ignored-win-amd64
    goos: [windows]
    goarch: [amd64]
    skip: true  # Don't actually build this

  # Dummy build for Windows arm64 GUI target
  - id: mkbrr-gui-windows-arm64-target
    main: ./cmd/mkbrr-gui/
    binary: ignored-win-arm64
    goos: [windows]
    goarch: [arm64]
    skip: true  # Don't actually build this

  # mkbrr-gui is built separately:
  # - macOS: using 'fyne package' on macOS runner (universal binary)
  # - Windows: using 'fyne-cross' on Linux runner
archives:
  # CLI tool archive (Targets all platforms defined in builds)
  - id: mkbrr
    # Only include the CLI tool build, not the dummy GUI builds
    ids:
      - mkbrr
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

  # macOS GUI Archive (Only applies to darwin platforms)
  - id: mkbrr-gui-darwin
    # Link to the macOS dummy build
    ids:
      - mkbrr-gui-darwin-target
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      universal
    files:
      - src: macos-artifact/mkbrr-gui-darwin-universal.zip
        dst: . # Include the zip in the archive root

  # Windows amd64 GUI Archive
  - id: mkbrr-gui-windows-amd64
    # Link to the Windows amd64 dummy build
    ids:
      - mkbrr-gui-windows-amd64-target
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      x86_64
    files:
      - src: dist/windows/amd64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

  # Windows arm64 GUI Archive
  - id: mkbrr-gui-windows-arm64
    # Link to the Windows arm64 dummy build
    ids:
      - mkbrr-gui-windows-arm64-target
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      arm64
    files:
      - src: dist/windows/arm64/mkbrr-gui.exe
        dst: mkbrr-gui.exe

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# TODO: Add nfpms config for mkbrr-gui if desired
