version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mkbrr
    env:
      - CGO_ENABLED=0
      - BUILDER
    # flags: # PGO flag removed during simplification, can be re-added if needed
    #   - -pgo=cpu.pprof
    main: ./cmd/mkbrr/
    binary: mkbrr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.CommitDate}}

  # mkbrr-gui is built separately:
  # - macOS: using 'fyne package' on macOS runner (universal binary)
  # - Windows: using 'fyne-cross' on Linux runner
archives:
  # CLI tool archive (Targets all platforms defined in builds)
  - id: mkbrr
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

  # macOS GUI Archive (Only applies to darwin platforms)
  - id: mkbrr-gui-darwin
    # No 'builds' key - only includes files listed below
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      universal
    files:
      - src: macos-artifact/mkbrr-gui-darwin-universal.zip
        dst: . # Include the zip in the archive root
    # Disable for non-macOS platforms
    overrides:
      - goos: linux
        enabled: false
      - goos: windows
        enabled: false

  # Windows amd64 GUI Archive
  - id: mkbrr-gui-windows-amd64
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      x86_64
    files:
      - src: dist/windows/amd64/mkbrr-gui.exe
        dst: mkbrr-gui.exe
    # Disable for non-Windows or non-amd64 platforms
    overrides:
      - goos: linux
        enabled: false
      - goos: darwin
        enabled: false
      - goos: windows
        goarch: arm64
        enabled: false

  # Windows arm64 GUI Archive
  - id: mkbrr-gui-windows-arm64
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-gui_
      {{- .Version }}_
      {{- .Os }}_
      arm64
    files:
      - src: dist/windows/arm64/mkbrr-gui.exe
        dst: mkbrr-gui.exe
    # Disable for non-Windows or non-arm64 platforms
    overrides:
      - goos: linux
        enabled: false
      - goos: darwin
        enabled: false
      - goos: windows
        goarch: amd64
        enabled: false

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/autobrr/mkbrr/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: mkbrr
    maintainer: autobrr
    description: |-
      mkbrr is a tool for creating, inspecting and modifying .torrent files.
    formats:
      - apk
      - deb
      - rpm
      - archlinux

# TODO: Add nfpms config for mkbrr-gui if desired
