name: Release

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/images/**"
      - "**.md"
  pull_request:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/images/**"
      - "**.md"

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
  GO_VERSION: "1.23.4"

permissions:
  contents: write
  packages: write

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Tests with Race Detection
        env:
          CGO_ENABLED: 1
        run: make test-race

  testother:
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, windows-latest ]
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ startsWith(matrix.os, 'windows') && 'D:\golang\go' || '' }}
      GOCACHE: ${{ startsWith(matrix.os, 'windows') && 'D:\golang\cache' || '' }}
      GOMODCACHE: ${{ startsWith(matrix.os, 'windows') && 'D:\golang\modcache' || '' }}
      USERPROFILE: ${{ startsWith(matrix.os, 'windows') && 'D:\homedir' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run Tests (MacOS)
        if: matrix.os == 'macos-latest'
        env:
          CGO_ENABLED: 1
        run: go test ./...

      #- name: Run Tests (Windows)
      #  if: matrix.os == 'windows-latest'
      #  env:
      #    CGO_ENABLED: 1
      #  run: go test -short ./...

      - name: Generate Test Summary
        if: matrix.os != 'windows-latest'
        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "unit-tests.xml"
        if: always() && matrix.os != 'windows-latest'

  pgo:
    name: Generate PGO Profile
    runs-on: ubuntu-latest
    needs: [ test, testother ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      # Create test data for profiling
      - name: Create test data
        shell: bash
        run: |
          mkdir -p test_data
          dd if=/dev/urandom of=test_data/test1.bin bs=1M count=100
          dd if=/dev/urandom of=test_data/test2.bin bs=1M count=100
          for i in {1..20000}; do dd if=/dev/urandom bs=1023 count=1 of=test_data/file$i.bin >/dev/null 2>&1; done

      - name: Generate Profile
        env:
          CGO_ENABLED: 0
        run: |
          # Build initial binary
          go build -o mkbrr ./cmd/mkbrr/

          # Run different workload scenarios
          ./mkbrr create test_data/test1.bin --cpuprofile=cpu1.pprof
          ./mkbrr create test_data/test2.bin --cpuprofile=cpu2.pprof
          ./mkbrr create test_data --cpuprofile=cpu3.pprof

          # Verify profiles exist
          if [ ! -f cpu1.pprof ] || [ ! -f cpu2.pprof ] || [ ! -f cpu3.pprof ]; then
            echo "Error: One or more profile files not generated"
            ls -la *.pprof
            exit 1
          fi

          # Merge profiles
          go tool pprof -proto cpu1.pprof cpu2.pprof cpu3.pprof > cpu.pprof

          # Verify final profile
          if [ ! -s cpu.pprof ]; then
            echo "Error: Final profile not generated or empty"
            exit 1
          fi

      - name: Upload pprof
        uses: actions/upload-artifact@v4
        with:
          name: pprof
          path: cpu.pprof
          
  build-gui-darwin:
    name: Build GUI for Darwin
    runs-on: macos-latest
    needs: [ test, testother ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          
      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest
        
      # Build GUI for macOS - two-step process for reliability
      - name: Build macOS GUI executable
        run: make build-gui

      - name: Package macOS GUI app bundle
        run: |
          fyne package --executable build/mkbrr-gui --os darwin --name mkbrr-gui --id com.autobrr.mkbrr --icon logo.png
          ls -la
          
      - name: Zip macOS app bundle
        run: |
          zip -r mkbrr-gui-darwin-universal.zip mkbrr-gui.app
          
      - name: Upload macOS GUI bundle
        uses: actions/upload-artifact@v4
        with:
          name: darwin-gui-artifact
          path: mkbrr-gui-darwin-universal.zip

  goreleaserbuild:
    name: Build distribution binaries
    runs-on: ubuntu-latest
    needs: [ pgo, build-gui-darwin ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Create destination directories
        run: |
          mkdir -p dist/darwin
          mkdir -p dist/windows

      - name: Download pprof
        uses: actions/download-artifact@v4
        with:
          name: pprof
          path: .
          
      - name: Download macOS GUI bundle
        uses: actions/download-artifact@v4
        with:
          name: darwin-gui-artifact
          path: ./macos-artifact/
          
      - name: Debug - List downloaded artifact
        run: |
          echo "Listing macos-artifact directory:"
          ls -la macos-artifact/ || echo "Directory macos-artifact not found or empty"
          echo ""
          echo "Listing full dist directory recursively:"
          find dist -type f -ls 2>/dev/null || echo "No files found in dist/"

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
          
      # Build GUI for Windows only
      - name: Build GUI for Windows
        run: |
          fyne-cross windows -arch=amd64,arm64 -app-id=com.autobrr.mkbrr --icon logo.png -output=mkbrr-gui ./cmd/mkbrr-gui/
          ls -la fyne-cross/bin/
          # Copy Windows binaries to a known location for GoReleaser
          mkdir -p dist/windows/amd64
          mkdir -p dist/windows/arm64
          cp fyne-cross/bin/windows-amd64/mkbrr-gui.exe dist/windows/amd64/
          cp fyne-cross/bin/windows-arm64/mkbrr-gui.exe dist/windows/arm64/ || echo "ARM64 Windows build may not be available"
      
      - name: Run GoReleaser build
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --skip=validate,publish --parallelism 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILDER: ${{ github.actor }}@github-actions

      - name: Run GoReleaser build and publish tags
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILDER: ${{ github.actor }}@github-actions

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: mkbrr
          path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.deb
            dist/*.rpm
